### PR TITLE
Some proposed abstractions

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by jonasfj** [comment]
@ckousik, please have a look at this... Tell me if it makes any sense...

Basically I propose that we have 3 abstractions:
- `Process`, deals with multiplexing the streams,
- `AbstractDebugger` implementations deals with interpreting gdb/mi, etc... for various debuggers,
- `Debugger` from `ui/debugger.js` deals with displaying user interface.

Clearly, when testing an `AbstractDebugger` implementation like `GDB` locally, we can provide a `Process` that just wraps a `child_process` object. And when running in the browser, we can create the `Process` object using something that talks over a websocket.

I'm actually tempted to propose:
https://github.com/taskcluster/docker-exec-websocket-server/
The server will connect to a docker container, and for each websocket it'll run `docker exec` with the given command (from query string)... It'll pipe stdin/stdout/stderr with some buffer control. And the client implementation supports demux the streams too..
So going from `DockerClient` to `Process` is pretty simple... Of course it would require us using a docker container when testing it (which is good for consistency, bad for ease of getting started).

Anyways, whenever we hook this up we just implement the `Process` object somehow.
Honestly, maybe we should just ignore the `Process` implementation details for now, and if we do a custom implementation not worry about details like buffering. If we get the abstraction correct we can always improve it.

**Comment by ckousik** [comment]
I incorrectly interpreted the etherpads I guess. I thought the remote process module was mainly going to be used for buffer control since the piping aspect itself was trivial.
- [ ] Abstract for `Process` using `DockerClient`. Configure the streams if necessary.
- [ ] Simple GDB interpreter ( just output, error, command etc), enough to run locally on docker

**Comment by jonasfj** [comment]
> I incorrectly interpreted the etherpads I guess. I thought the remote process module was mainly going to be used for buffer control since the piping aspect itself was trivial.

@ckousik, yeah, but there is both a client-side and a server-side to buffering when piping over a websocket..

Note: My ramblings on the etherpads aren't always sane... he he... Sometimes things just get out without being fully thought through. But that's okay...

Let me know what you think of these abstractions... Is it sane, what would we add... how should we structure tests..

**Comment by ckousik** [comment]
# Process
- I feel testing the `stdin` side of `Process` won't be hard as we can intentionally cause the buffer to fill and test for an event asking to stop writing to `stdin`. We will also need a `drain` event `stdin.once('drain', ... )` to know when to start writing again. So we could combine this into a single test case. 
- For `stdout` and `stderr` we could connect process to a program the writes random bytes to these streams and pipe them to a client. Then we test for a message asking `stdout` and `stderr` to be paused. That way we can be certain that the buffer control works fine on both ends.
- To check for an out of bounds condition we simply pause `stdout` and `stderr` and make the process keep writing to them. This will fill up the internal buffer. Then we test for an event which emits an out of bounds message.
- Exit is trivial to test. We could use `kill` to send different messages and check for the exit event.

# AbstractDebugger

I don't really have any idea as of now but I'd like to take my time with this.

**Comment by jonasfj** [comment]
closing all PRs...

**Pull request closed without merging**
