### PR TITLE
Adds a remote_process module. Works with spawn.

### PR DESCRIPTION
**Pull request by ckousik**
```
modified:   package.json
new file:   src/remote_process.js
modified:   src/test-client.js
modified:   src/test-server.js
```

### CODE REVIEW

**Comment by ckousik** [comment]
I have a lot more to add to this but I just want to know if this is an okay way to go about this...

**Comment by ckousik** [comment]
I read the node js source and fork, exec, and execFile all eventually call spawn to create the subprocess, so with a few minor additions I should be able to integrate them into the module too.

**Comment by jonasfj** [comment]
As I come to think about this... we could probably reuse: https://github.com/taskcluster/docker-exec-websocket-server/
This is already implemented in our workers...

And say that the server has to operate on a docker container... Which also makes it easier to reproduce the same debugger version between different development environments...

I'll stick my head in the thinking box and suggests some abstractions today.. sorry for the delay..

**Comment by jonasfj** [comment]
I think there is both a `RemoteProcessServer` and a `RemoteProcessClient` aspect to the idea.
ie. on the server we would do:

``` js
server.on('connection', socket => {
  let proc = new RemoteProcessServer(socket, ['gdb', '-q', '--interpreter=mi']);
  proc.spawn();
});
```

And in the client we would do:

``` js
let ws = require('ws'); 
let socket = new ws('ws://localhost:8080');
let proc = new RemoteProcessClient(socket);
proc.on('ready', () => {
  // proc is connected have started...
});
proc.stdin  // This is a stream object
proc.stdout // This is a stream object
proc.stderr // This is a stream object
proc.on('exit', code => {
  // process have exited (and websocket is closed)
});
```

If you see: https://github.com/taskcluster/docker-exec-websocket-server/
That is effectively what it is.. Except the server won't run `child_process.spawn` it'll use `docker exec` to run the command...
And the `Process` abstraction proposed in https://github.com/taskcluster/react-gdb/pull/3 is trivial to implement with `RemoteProcessClient`.

Note: Maybe we don't have to implement the `RemoteProcessClient/Sever` as the first thing... We could (A) run all the debugger (gdb/mi) tests locally... And when testing in a browser we could use: https://github.com/taskcluster/docker-exec-websocket-server/

And we could ignore buffering in `RemoteProcessClient/Sever` as long as things are exposed as stream objects we can always add that later. If we use `through2` then we can be sure things are valid stream objects -- I think, node streams are hard :)

**Pull request closed without merging**
